### ISSUE TITLE
SVG conversion broken for mirrored paths with opposite winding order

### ISSUE THREAD

**Issue by lyuma** [jaywcjlove/svgtofont#165]
Here is the original icon, likely created by mirroring the left eye to create the right eye.
Download "bad.svg": https://user-images.githubusercontent.com/39946030/172930821-ec22550d-76d9-41e7-898c-22f7310df846.svg
![Godot_icon_bad_winding](https://user-images.githubusercontent.com/39946030/172930821-ec22550d-76d9-41e7-898c-22f7310df846.svg)

Here is the same icon, fixed by hand to have matching vertex order in the right eye as left:
Download "fixed.svg": https://user-images.githubusercontent.com/39946030/172931900-d648e8c6-ce69-4373-bda7-cced07a34974.svg
![Godot_icon_fixed](https://user-images.githubusercontent.com/39946030/172931900-d648e8c6-ce69-4373-bda7-cced07a34974.svg)

You can see the result here: The first icon is the "fixed" one. The second with missing eye is the "bad" original icon:
![godot_icon_fontdrop_winding](https://user-images.githubusercontent.com/39946030/172932063-997351bd-2739-44d8-86d2-8d272af2edfa.png)
The same bug is present on Glyphter. It is possible their backend uses some code from svgtofont.

To test, save the "fixed" icon as svg/a.svg and the "bad" icon as svg/b.svg. Then, run this command:
```
svgtofont --sources ./svg --output ./font --fontName godot-icon
```
This command successfully creates .ttf. Please ignore the exception: it happens after the .ttf is generated, so there is no problem for me.

Here are the specific paths which I changed by hand between the "bad" and "fixed" SVG documents.

Original "bad":
```svg
<svg><g><path fill="#ffffff" d="
M-247.2-10.7c0,50.1-40.6,90.7-90.8,90.7c-50.1,0-90.7-40.6-90.7-90.7c0-50.1,40.6-90.7,90.7-90.7C-287.8-101.5-247.2-60.9-247.2-10.7
M-1.6-10.7c0,50.1,40.6,90.7,90.8,90.7c50.1,0,90.7-40.6,90.7-90.7c0-50.1-40.6-90.7-90.7-90.7C38.9-101.5-1.6-60.9-1.6-10.7"/>
<path fill="#414042" d="
M-269-5.3c0,33.2-26.9,60.2-60.2,60.2c-33.2,0-60.2-26.9-60.2-60.2c0-33.2,26.9-60.2,60.2-60.2C-296-65.6-269-38.6-269-5.3
M 20-5.3c0,33.2,26.9,60.2,60.2,60.2c33.3,0,60.2-26.9,60.2-60.2c0-33.2-26.9-60.2-60.2-60.2C47-65.6,20-38.6,20-5.3"/></g></svg>
```

"fixed" version:
```svg
<svg><g><path fill="#ffffff" d="
M-247.2-10.7c0,50.1-40.6,90.7-90.8,90.7c-50.1,0-90.7-40.6-90.7-90.7c0-50.1,40.6-90.7,90.7-90.7C-287.8-101.5-247.2-60.9-247.2-10.7
M176-10.7c0,50.1-40.6,90.7-90.8,90.7c-50.1,0-90.7-40.6-90.7-90.7c0-50.1,40.6-90.7,90.7-90.7C135-101.5,176-60.9,176-10.7"/>
<path fill="#414042" d="
M-269-5.3c0,33.2-26.9,60.2-60.2,60.2c-33.2,0-60.2-26.9-60.2-60.2c0-33.2,26.9-60.2,60.2-60.2C-296-65.6-269-38.6-269-5.3
M 140-5.3c0,33.2-26.9,60.2-60.2,60.2c-33.2,0-60.2-26.9-60.2-60.2c0-33.2,26.9-60.2,60.2-60.2C113-65.6,140-38.6,140-5.3"/></g></svg>
```

**Comment by schmidt-oliver** [comment]
Hi @lyuma, please try using [SVGFixer](https://github.com/oslllo/svg-fixer) to outline the icons before converting them to font. It worked like a charm in my case.

**Comment by jaywcjlove** [comment]
@schmidt-oliver thx!

- https://github.com/jaywcjlove/svgtofont/issues/195#issuecomment-1609418046

**Comment by Bolt-unread** [comment]
How can I disable alphabetical sorting or just have newly added svg files added to the end of the generated css file?
