### ISSUE TITLE
svgtofont有方法接受svg对象而不是路径吗

### ISSUE THREAD

**Issue by LikeDreamwalker** [jaywcjlove/svgtofont#169]
想要通过用户上传.svg + 预览 + 导出的方式，貌似现在只接受通过路径方式传入svg

**Comment by jaywcjlove** [comment]
> 想要通过用户上传.svg + 预览 + 导出的方式，貌似现在只接受通过路径方式传入svg

没有明白什么意图

**Comment by xty1992a** [comment]
楼主意思应该是要一个不带io，用于前端处理，接受svg字符串，输出Blob之类的内核。

**Comment by catanswer** [comment]
现在生成时src字段传入的是一个文件夹路径，将该文件中的svg图片进行操作
楼主想要的应该是添加一个配置字段传入某个或多个图片文件路径，进行后续生成
