### ISSUE TITLE
Unexpected Result while converting an svg to font

### ISSUE THREAD

**Issue by alapanbagchi** [jaywcjlove/svgtofont#180]
I was trying to convert a bunch of svgs to font using this code but it has led to some weird results

```   
const uploadPath = path.join(__dirname, `../temp/svg/${userid}`)
const fontPath = path.join(__dirname, `../temp/fonts/${userid}`)

const options: SvgToFontOptions = {
            src: uploadPath,
            dist: fontPath,
            fontName: name,
            useNameAsUnicode: true,
        }
        await createSVG(options)
        const ttf = await createTTF(options)
        await createWOFF(options, ttf)
        await createWOFF2(options, ttf)
        await createEOT(options, ttf)

```

Ths is the original svg used

![dog1](https://user-images.githubusercontent.com/85439790/189292547-668ea8f0-3874-469b-a564-8fe73f059d1f.svg)

This is the result obtained
![image](https://user-images.githubusercontent.com/85439790/189290508-1fac2171-e416-463d-b635-ee8d31dac31d.png)

**Comment by jaywcjlove** [comment]
@alapanbagchi If you convert to fonts, you can only use `<path>`, many tags of svg cannot be used.

**Comment by alapanbagchi** [comment]
Hi, thanks for clearing that up
I managed to fix that issue by converting it into one long single `<path>` which fixed the above mentioned issue. However I encountered a new problem.

So, here is the new svg
![test](https://user-images.githubusercontent.com/85439790/189408991-558166d9-75e4-4056-b739-9536e43a37db.svg)

and this is the resulting font
![image](https://user-images.githubusercontent.com/85439790/189409258-044b7339-aa2b-4350-b8bd-3ea62d8c7575.png)

**Comment by jaywcjlove** [comment]
In fonts, `fill-rule="evenodd"` for svg is also not supported.

**Comment by alapanbagchi** [comment]
That makes sense, thanks for your help

**Comment by schmidt-oliver** [comment]
Hi @alapanbagchi, please try using [SVGFixer](https://github.com/oslllo/svg-fixer) to outline the icons before converting them to font. It worked like a charm in my case.

**Comment by Opty1712** [comment]
> Hi @alapanbagchi, please try using [SVGFixer](https://github.com/oslllo/svg-fixer) to outline the icons before converting them to font. It worked like a charm in my case.

confirm it works!
```js
await SVGFixer(resolve(process.cwd(), 'svg'), resolve(process.cwd(), 'tmp'), {
  showProgressBar: true,
  throwIfDestinationDoesNotExist: false,
}).fix();
```
