### ISSUE TITLE
The classNamePrefix should`t join name with "-"

### ISSUE THREAD

**Issue by xty1992a** [jaywcjlove/svgtofont#181]
[code](https://github.com/jaywcjlove/svgtofont/blob/777c5ef11f0c256c9178fc0923b2ac2514441d5e/src/index.ts#L205) here

maybe should add a new option like "hyphen" (default set "-") to allow people fully controll the className

**Comment by jaywcjlove** [comment]
@xty1992a Upgrade `v3.18.0`

**Comment by xty1992a** [comment]
wow so efficiency!

**Comment by xty1992a** [comment]
老哥其实我是想干掉这个连字符来的...

取默认值用??比较好吧。现在传值""不生效。

**Comment by xty1992a** [comment]
同样的，prefix如果想取消（即直接使用svg名称作为className）现在也会被fontName覆盖
