### ISSUE TITLE
请教2个问题，谢谢！

### ISSUE THREAD

**Issue by lecykx** [jaywcjlove/svgtofont#188]
1、生成icon文件后，怎么获取每个icon相关信息，比如fontclass，unicode等
2、怎么单独去修改某个icon的相关信息，比如fontclass，unicode等

PS：我在弄一个类似iconfont的平台项目

**Comment by jaywcjlove** [comment]
@lecykx 这个没有暴露出来，倒是生成了一个 `*.json` 文件

https://github.com/uiwjs/icons/blob/gh-pages/w-icon.json

这个 `.json` 文件只是 `svg path` 的索引，需要每个图标的相关信息，可以生成一个 `data.json` 或者 `data.js` 把需要的信息包含到里面去

**Comment by jaywcjlove** [comment]
修改，需要重新生成一遍吧，好像没有修改字体里面的某个信息的API
@lecykx

**Comment by lecykx** [comment]
请教一下，json文件是怎么生成的呀？

**Comment by lecykx** [comment]
或者说怎么读取到每个图标相关信息

**Comment by jaywcjlove** [comment]
你不是要类似iconfont的平台项目？fork 过去改吧改吧就有了，很简单的，本身工具本身不支持生成这种数据，需要支持？

**Comment by lecykx** [comment]
我看readme那有说生成json文件，但是我没看到有生成，所以请教下你

**Comment by lecykx** [comment]
看到了是outSVGPath，看是否满足，不满足我再fork改，谢谢了

**Comment by jaywcjlove** [comment]
@lecykx 添加了 参数配置设置生成 图标数据，`./dist/info.json`

```js
{
  "adobe": {
    "encodedCode": "\\ea01",
    "prefix": "svgtofont",
    "className": "svgtofont-adobe",
    "unicode": "&#59905;"
  },
  ...
}
```
