### ISSUE TITLE
dist所在的文件夹里面文件会被删除

### ISSUE THREAD

**Issue by kallsave** [jaywcjlove/svgtofont#2]
运行svgtofont后dist所在的文件夹里面的文件会被删除

**Comment by jaywcjlove** [comment]
@kallsave 应该是别的脚本搞的吧，默认对 `fonts` 操作其它不回清空删除。

**Comment by jaywcjlove** [comment]
@kallsave 看错了，是默认 dist 目录的, 你可以指定到别的目录生成字体

```js
const svgtofont = require("svgtofont");
 
svgtofont({
  src: path.resolve(process.cwd(), "icon"), // svg path
  dist: path.resolve(process.cwd(), "fonts"), // output path
  fontName: "svgtofont", // font name
  css: true, // Create CSS files.
}).then(() => {
  console.log('done!');
});
```

**Comment by kallsave** [comment]
@jaywcjlove 我就依赖了svgtofont,  可以去掉清空dist目录的功能吗 因为有时候字体统一放在一个文件夹了 可能还有不用svgtofont生成的字体文件都放里面

**Comment by jaywcjlove** [comment]
你使用 `svgtofont` 不生成字体？怎么回清空 `dist` 目录呢？

不过我已经改了默认输出目录为 `fonts`, `dist` 却是容易与其它目录发生冲突。`+ svgtofont@1.1.11`

**Comment by jaywcjlove** [comment]
@kallsave 你可以使用下面API 自己手动生成，想生成到什么目录就生成到什么目录，不会有清空目录的操作了。

```js
const {
  createSVG, 
  createTTF, 
  createEOT, 
  createWOFF, 
  createWOFF2, 
  createSvgSymbol
} = require("svgtofont/src/utils");
```

**Comment by kallsave** [comment]
@jaywcjlove  我的demo地址: https://github.com/kallsaver/my-learn/tree/master/svgtofont-learn
你在fonts目录下新建一个txt文件或者其他文件都行 会自动删除

**Comment by jaywcjlove** [comment]
@kallsave 是的新版 `svgtofont@1.1.12`

**Comment by kallsave** [comment]
@jaywcjlove   ok  肥肠好用 thanks~
