### ISSUE TITLE
只生成了 svg ttf eot 文件  其他文件创建失败

### ISSUE THREAD

**Issue by zwp-hz** [jaywcjlove/svgtofont#20]
node：v10.8.0
svgtofont: v1.3.0

A fontHeight of at least than 1000 is recommended, otherwise further steps (rounding in svg2ttf) could lead to ugly results. Use the fontHeight option to scale icons.
Font created
SUCCESS SVG font successfully created! /Users/zhuweipeng/qtshe-project/qts-admin/fonts1571797765738/font1571797765738.svg
SUCCESS TTF font successfully created! /Users/zhuweipeng/qtshe-project/qts-admin/fonts1571797765738/font1571797765738.ttf
SUCCESS EOT font successfully created! /Users/zhuweipeng/qtshe-project/qts-admin/fonts1571797765738/font1571797765738.eot
Checksum error in glyf

**Comment by jaywcjlove** [comment]
@zwp-hz 看不到你的工程，不知道 你这个  `fontHeight` 参数怎么设置的

**Comment by zwp-hz** [comment]
是这样的
`svgtofont({
      src: path.resolve(process.cwd(), `files/${timestamp}`), // svg path
      dist: path.resolve(process.cwd(), `fonts${timestamp}`), // output path
      fontName: `font${timestamp}`, // font name
      css: true, // Create CSS files.
      outSVGReact: true,
      outSVGPath: true,
      startNumber: 20000, // unicode start number
      svgicons2svgfont: {
        fontHeight: 1000,
        normalize: true
      }
    })
      .then(() => {
        console.log('done!')
      })
      .catch(err => {
        console.log(err)
      })
`

**Comment by zwp-hz** [comment]
``svgtofont({
      src: path.resolve(process.cwd(), `files/${timestamp}`), // svg path
      dist: path.resolve(process.cwd(), `fonts${timestamp}`), // output path
      fontName: `font${timestamp}`, // font name
      css: true, // Create CSS files.
      outSVGReact: true,
      outSVGPath: true,
      startNumber: 20000, // unicode start number
      svgicons2svgfont: {
        fontHeight: 1000,
        normalize: true
      }
    })
      .then(() => {
        console.log('done!')
      })
      .catch(err => {
        console.log(err)
      })
``

**Comment by zwp-hz** [comment]
`svgtofont({
      src: path.resolve(process.cwd(), `files/${timestamp}`), // svg path
      dist: path.resolve(process.cwd(), `fonts${timestamp}`), // output path
      fontName: `font${timestamp}`, // font name
      css: true, // Create CSS files.
      outSVGReact: true,
      outSVGPath: true,
      startNumber: 20000, // unicode start number
      svgicons2svgfont: {
        fontHeight: 1000,
        normalize: true
      }
    })
      .then(() => {
        console.log('done!')
      })
      .catch(err => {
        console.log(err)
      })
`

**Comment by jaywcjlove** [comment]
@zwp-hz  没有工程，我不知道怎么调试，你可以不设置 `svgicons2svgfont` 使用默认值，试一试。

或者你把你的工程上传，我帮你调试一下

**Comment by zwp-hz** [comment]
追加 svgicons2svgfont 的区别在于是否有fontHeight的提醒， 生产的文件内容是一致的。
我是在koa中去执行的 ，clone 代码 跑起来是正常的。

**Comment by jaywcjlove** [comment]
@zwp-hz 没有工程我无法调试你的问题。

**Comment by zwp-hz** [comment]
> @zwp-hz 没有工程我无法调试你的问题。

我创建了一个简易的项目，地址是 ### https://github.com/zwp-hz/svgtofont-test

**Comment by jaywcjlove** [comment]
@zwp-hz 我注释了下面代码，生成就没有毛病，是你业务代码有问题。

![image](https://user-images.githubusercontent.com/1680273/67363079-258b4480-f59f-11e9-8840-3e9846675310.png)
