### ISSUE TITLE
Npm script and .svgtofontrc file

### ISSUE THREAD

**Issue by bckthomas** [jaywcjlove/svgtofont#211]
Hi,
I use svgtofont 4.0.0 with a npm script "svgfont": "svgtofont --sources Resources/Private/Src/Icons --output Resources/Public/Fonts"

I have this config in config/.svgtofontrc
```
{
  "fontName": "icon",
  "css": true
}
```
When I execute **_npm run svgfont_**, font is created with svgtofont name, not icon, and the css files are not created. It seems that the config file is not used.

Can someone help me please ?
Thanks

**Comment by jaywcjlove** [comment]
@bckthomas The error is not reproducible, please provide an example of how the error can be reproduced

**Comment by bckthomas** [comment]
Ok, my bad, svg file contained errorrs
