### ISSUE TITLE
svgtofont is returning...void?

### ISSUE THREAD

**Issue by ericmorand** [jaywcjlove/svgtofont#213]
I'm testing svgtofont and I don't quite understand how the TypeScript/Javascript API is supposed to work: according to the type definition, `svgtofont` is a function that returns `Promise<void>`.

How am I expected to retrieve the built font if `svgtofont` doesn't return anything? Is this a bug in the type definition?

**Comment by jaywcjlove** [comment]
@ericmorand No API is provided. After the generation is completed, you can read it yourself based on the generated file.

If you need to provide what kind of API, you can make a request

**Comment by ericmorand** [comment]
Thanks a lot.
