### ISSUE TITLE
Having multiple source folders

### ISSUE THREAD

**Issue by lhtdesignde** [jaywcjlove/svgtofont#219]
Hi, first off, thanks for the great package! It does everything I need!
I have a question regarding the sources in the npm script. At the moment I have the following script in the `package.json`:

`"font": "svgtofont --sources ./src/assets/icons/** --output ./src/assets/iconfont"`

```
  └── icons
      ├── folder-A
          └── icon.svg
      ├── folder-B
           └── icon.svg
      └── folder-C
         └── icon.svg
```

That works but not as expected. In the folder `icons` are another 5 folders with icons. At the moment it only gets the icons from the first folder and ignores the rest. Is there a way to make it use all folders and not just the first one within `icons`?
Thanks!

**Comment by jaywcjlove** [comment]
@lhtdesignde You can first use the [`cpy-cli`](https://www.npmjs.com/package/cpy-cli) command to copy the image to a directory, and then run `svgtofont`
