### ISSUE TITLE
可以生成无需添加class或者unicode就能使用的字体吗

### ISSUE THREAD

**Issue by ilp64** [jaywcjlove/svgtofont#22]
我有 0-9 这 10 个数字的 svg, 想把这 10 个 svg 转成一个字体文件，供页面上的阿拉伯数字使用。

重点就是不要像使用 iconfont 那样，还得加 class 或者写 unicode，就是 2 步到位:

* 页面加载这个字体文件
* 给需要的元素指定 font-family

就像使用系统字体差不多的形式，请问可以吗😅

**Comment by jaywcjlove** [comment]
@ilp64 你普通指定字体也是要使用 class 设置字体的样式吧。据我所知没有别的方法了吧。

**Comment by ilp64** [comment]
@jaywcjlove 是的，貌似得去创建字体了
