### ISSUE TITLE
unify width and height

### ISSUE THREAD

**Issue by xtrashild** [jaywcjlove/svgtofont#226]
Hi, 

no matter which font-size I use, I end up having and icon that has different width and height, usually the height is correct 
but the width is stretched.

examples:

I set font-size for the icon to be 10px
I expect 10x10 I get 12.8x10

I set the font-size for the icon to be 12px
I expect 12x12 I get 15.37x12

is there a property I can set to prevent the stretching?

**Comment by jaywcjlove** [comment]
I have not reproduced the issue you described. I guess it might be necessary to check the size of the icon.
