### ISSUE TITLE
4.x版本修复cheerio.load报错的问题

### ISSUE THREAD

**Issue by catanswer** [jaywcjlove/svgtofont#246]
由于5.x版本只支持ES模块了
项目特性只能使用commonjs，所以只能使用4.x的版本
但是4.x版本的cheerio会出现[bug237](https://github.com/jaywcjlove/svgtofont/issues/237)的问题
所以还望4.x版本能再更新修复一下

**Comment by jaywcjlove** [comment]
@catanswer 发布了一个 `v4.2.3` 版本，更新试一试

**Comment by catanswer** [comment]
可以了，感谢感谢
