### ISSUE TITLE
No option to remove timestamp in generated files

### ISSUE THREAD

**Issue by epaul-imc** [jaywcjlove/svgtofont#250]
Hi,

I'm generating files but when I add a new icon and regenerate, I don't want to add the timestamp in any of the files.

Is there a way to do this ?

**Comment by jaywcjlove** [comment]
@epaul-imc Upgrade `v6.2.0`

```ts
/**
 * @type {import('svgtofont').SvgToFontOptions}
 */
export default {
  fontName: "iconfont",
  css: {
    //hasTimestamp: "v1.2.3"
    hasTimestamp: false
  }
}
```

https://github.com/jaywcjlove/svgtofont/blob/83521159ee38d9ea1fe72b6d92bcc417d9b2ca79/src/utils.ts#L283-L288

**Comment by epaul-imc** [comment]
Thank you!

**Comment by epaul-imc** [comment]
Thank you very much!
