### ISSUE TITLE
feature_reqeust: 递归的查找子目录下的svg

### ISSUE THREAD

**Issue by Certseeds** [jaywcjlove/svgtofont#251]
hey, 查看代码发现filterSvgFiles只查询目录下一层的svg, 希望能够递归的查询目录下所有的svg

**Comment by jaywcjlove** [comment]
@Certseeds 图标名称容易冲突，可以通过 https://www.npmjs.com/package/cpy-cli 进行复制到一个一层目录下

**Comment by Certseeds** [comment]
> @Certseeds 图标名称容易冲突，可以通过 https://www.npmjs.com/package/cpy-cli 进行复制到一个一层目录下

那可以合一下 #253 , 把现在的默认行为加README里
