### ISSUE TITLE
svgicons2svgfont settings not adopted ?

### ISSUE THREAD

**Issue by jdriesen** [jaywcjlove/svgtofont#27]
Hi @jaywcjlove ,

First of all, thanks for sharing this useful software ! 

Though, I'm have a small issue.
It seems the settings from the ```svgicons2svgfont``` object aren't adopted in the generated css file.

Please take a look at this printscreen.
![image](https://user-images.githubusercontent.com/1137648/83149791-d1c77780-a0fa-11ea-859b-e4224c4c37a5.png)

Can you please tell give me some help / a hint ?

Thanks in advance for your reply,

Kind regards,
Johnny Driesen
Belgium

**Comment by jaywcjlove** [comment]
https://github.com/jaywcjlove/svgtofont/blob/ed6464cc9d7d3d6244f46234040e67b803d917fd/src/index.js#L30-L31

@jdriesen Invalid `fontName` setting?

**Comment by jdriesen** [comment]
Hi @jaywcjlove ,

Thanks for your quick reply.
Really appreciated !

I upgraded the  ```svgtofont``` dependency to version ```^2.0.0``` in my package.json.
Unfortunately, I still can't make it work ...

If I can ask ... 
Is your documentation on https://github.com/jaywcjlove/svgtofont still 100% up to date ?

FYI: I'm using your package with NodeJS. 
(and I literally copy pasted your "extended" example")

Thanks in advance for your answer,

Kind regards,
Johnny Driesen.

**Comment by jaywcjlove** [comment]
I passed the parameters to the [svgicons2svgfont](https://www.npmjs.com/package/svgicons2svgfont) package for processing.

**Comment by jaywcjlove** [comment]
You can look at [svgicons2svgfont](https://www.npmjs.com/package/svgicons2svgfont)  package.

**Comment by jdriesen** [comment]
Your documentation is 100% up to date ? (in particular, the svgicons2svgfont object) ?

**Comment by jdriesen** [comment]
My apologies, @jaywcjlove .
Did some deeper research and the mistake was at my side...
(SVG generation has nothing to do with settings in the generated .CSS file)

**This issue can be closed**.

Thanks again for your support.

**Comment by jaywcjlove** [comment]
👍
