### ISSUE TITLE
Typo in 'clssaNamePrefix' option

### ISSUE THREAD

**Issue by PunyFlash** [jaywcjlove/svgtofont#28]
Hello!
I think `classNamePrefix` what is meant. Struggled a few minutes to understand is typo only in markdown or in code in general.
The variable with a typo is working for me. I think this should be fixed.
![image](https://user-images.githubusercontent.com/14828695/86522190-e0741d80-be62-11ea-84f5-531894e62d76.png)

**Comment by jaywcjlove** [comment]
@PunyFlash  thx! Upgrade `📦 svgtofont@2.1.0`
