### ISSUE TITLE
创建图标完成后promise的then没有执行

### ISSUE THREAD

**Issue by kallsave** [jaywcjlove/svgtofont#3]
我记得上个版本是可以的,加了emptyDist这个字段的新版本不执行了
svgtofont({
    src: item,
    dist,
    fontName,
    css: true,
    startNumber: 20000,
    emptyDist: false
  }).then(() => {
    console.log('done没有执行')
  }).catch((err) => {
    // console.log(err)
  })

**Comment by jaywcjlove** [comment]
@kallsave 应该是没有 website 参数吧

**Comment by kallsave** [comment]
@jaywcjlove  上个版本可以的

**Comment by jaywcjlove** [comment]
@kallsave 更新 `+ svgtofont@1.1.13` 试一试

**Comment by kallsave** [comment]
@jaywcjlove   ok thanks~
