### ISSUE TITLE
Heroicons SVGs with stroke lines...

### ISSUE THREAD

**Issue by macCesar** [jaywcjlove/svgtofont#33]
Excellent tool!!!... I've created my first font from a bunch of SVGs on the first try!!!

But I have a problem with [Heroicons](https://github.com/tailwindlabs/heroicons).

The resulting fonts ( at least the .ttf versions ) were not converted correctly because most of the designs contain stroke lines instead of outlines.

**Is there a way to auto-convert them to outlines before creating the font file ???**

Thanks!!

**Comment by jaywcjlove** [comment]
@macCesar I handled it through `Sketch`.

**Comment by macCesar** [comment]
Sketch the drawing app ???

I was hopping something automated...

My script depends on various packages including heroicons ( npm i heroicons ).

So I don't want to edit the SVG files everytime it gets updated! 😬

**Comment by macCesar** [comment]
I'm going to test this package:

https://www.npmjs.com/package/svg-outline-stroke

**Comment by jaywcjlove** [comment]
@macCesar Welcome to submit PR. thx!

**Comment by macCesar** [comment]
Sure thing!! 👍

**Comment by schmidt-oliver** [comment]
> I'm going to test this package:
> 
> https://www.npmjs.com/package/svg-outline-stroke

That package didn't work for me. After some days of work i found a solution based on https://docs.oslllo.com/svg-fixer/master/#/ . No changes need in `svgtofont`.

**Comment by jaywcjlove** [comment]
@schmidt-oliver thx!

https://github.com/oslllo/svg-fixer

**Comment by schmidt-oliver** [comment]
I think it can be closed as well.

**Comment by jaywcjlove** [comment]
- https://github.com/jaywcjlove/svgtofont/issues/195#issuecomment-1609418046
