### ISSUE TITLE
"unicodeStart" or "startNumber" configuration doesn't work.

### ISSUE THREAD

**Issue by bwlfhu** [jaywcjlove/svgtofont#50]
i want my iconfont begin with the unicode i specified, but it doesn't work when i use "unicodeStart" or "startNumber" configuration.

![image](https://user-images.githubusercontent.com/10275564/94429773-6fc07100-01c5-11eb-89ad-7e985a40ffe3.png)

**Comment by jaywcjlove** [comment]
@bwlfhu Upgrade `+ svgtofont@3.2.1`


~~`unicodeStart`~~ => `startUnicode`
