### ISSUE TITLE
Feature request:  Generate typescript enums

### ISSUE THREAD

**Issue by redwoodfavorite** [jaywcjlove/svgtofont#62]
Proposal: Generate Typescript file with enum for icon class names.  Copped this idea from a similar library.

```ts
export enum Icon {
  SomeIcon: 'my-font-some-icon'
}
```

Advantages:
- Users would get Typescript errors if an icon was removed or renamed
- No code changes required when changing prefixes

**Comment by jaywcjlove** [comment]
@redwoodfavorite This is a good idea

**Comment by jaywcjlove** [comment]
@redwoodfavorite Welcome to submit PR.

**Comment by jaywcjlove** [comment]
@redwoodfavorite thx! Upgrade `+ svgtofont@3.8.0`
