### ISSUE TITLE
Attribute fill-rule seems to be ignored

### ISSUE THREAD

**Issue by vitto** [jaywcjlove/svgtofont#79]
I'm trying to build a font with some svg exported from Figma, as flatten shape, when I export it from Figma it generates this svg as a terminal icon:

```svg
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M2 6C2 4.89543 2.89543 4 4 4H20C21.1046 4 22 4.89543 22 6V18C22 19.1046 21.1046 20 20 20H4C2.89543 20 2 19.1046 2 18V6ZM4 6H6V8H4V6ZM14 6H8V8H14V6ZM4 10H10V12H4V10ZM20 6H16V8H20V6Z" fill="black"/>
</svg>
```

When I use it to build the font, no errors are thrown, but when I try to see the icon it is show like `fill-rule="evenodd"` is ignored, resulting like this svg:

```svg
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path clip-rule="evenodd" d="M2 6C2 4.89543 2.89543 4 4 4H20C21.1046 4 22 4.89543 22 6V18C22 19.1046 21.1046 20 20 20H4C2.89543 20 2 19.1046 2 18V6ZM4 6H6V8H4V6ZM14 6H8V8H14V6ZM4 10H10V12H4V10ZM20 6H16V8H20V6Z" fill="black"/>
</svg>
```

Would it be nice if this can be fixed.

It seems to be an existing problem also for other libs: https://github.com/nfroidure/svgicons2svgfont/issues/62

**Comment by vitto** [comment]
I found a workaround from Figma for it in case someone need to fix it with [Fill Rule Editor plug-in](https://www.figma.com/community/plugin/771155994770327940/Fill-Rule-Editor), but it would be nice if there is an automatic way to fix it.

**Comment by jaywcjlove** [comment]
@vitto Some attributes converted to font svg are lost.

**Comment by schmidt-oliver** [comment]
Hi @vitto, please try using [SVGFixer](https://github.com/oslllo/svg-fixer) to outline the icons before converting them to font. Or use a [figma plugin](https://www.figma.com/community/plugin/771155994770327940/Fill-Rule-Editor) to change the winding rule from `even-odd` to `non-zero`.

**Comment by jaywcjlove** [comment]
- https://github.com/jaywcjlove/svgtofont/issues/195#issuecomment-1609418046
