### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '~/svgtofont/dist/svgtofont.svg'

### ISSUE THREAD

**Issue by Xing-He** [jaywcjlove/svgtofont#8]
克隆仓库执行 `npm run test` 提示没有路径, `/svgtofont/dist/svgtofont.svg`，调试了下发现是配置的`output` 输出目录没有检测是否存在

![image](https://user-images.githubusercontent.com/11990205/52956539-60aef580-33ca-11e9-8e6f-e5e51f04beba.png)

**Comment by jaywcjlove** [comment]
@Xing-He thx! 了解
